(function (root) {
  "use strict";

  // Base piece shapes, local coordinates, CCW winding.
  // unit = leg length of the small triangle.
  var SHAPES = {
    largeTri: [[0, 0], [2, 0], [0, 2]],
    mediumTri: [[0, 0], [2, 0], [1, 1]],
    smallTri: [[0, 0], [1, 0], [0, 1]],
    square: [[0, 0], [1, 0], [1, 1], [0, 1]],
    parallelogram: [[0, 0], [1, 0], [2, 1], [1, 1]]
  };

  // How many degrees a shape can be rotated and still look identical
  // (used so e.g. a square doesn't force one "correct" rotation out of 4).
  var SHAPE_SYMMETRY = {
    largeTri: 360,
    mediumTri: 360,
    smallTri: 360,
    square: 90,
    parallelogram: 180
  };

  // Mirroring a parallelogram produces a genuinely different (chiral) piece
  // that no rotation can reproduce, so its flip state must match the target
  // exactly. Every other shape has a mirror symmetry axis, so flipping it is
  // either a total no-op (mediumTri, square - the axis runs through the
  // shape's own centroid the way our flip mirrors it) or exactly reproduces
  // some rotated unflipped orientation (largeTri/smallTri, whose axis runs
  // diagonally rather than through the vertical mirror we apply - two
  // reflections at 45 degrees to each other compose into a 90 degree
  // rotation). This offset is added to a flipped piece's angle before
  // comparing it to the target, so completion only cares how the piece
  // actually looks, never whether flip was the way the player got there.
  var CHIRAL_SHAPES = { parallelogram: true };
  var SHAPE_FLIP_ROTATE_OFFSET = {
    largeTri: 90,
    mediumTri: 0,
    smallTri: 90,
    square: 0
  };

  // Cosmetic colors per shape; index = which physical copy (0-based) for
  // shapes that appear twice in a set. Purely visual - matching is shape-based.
  var SHAPE_COLORS = {
    largeTri: ["#e74c3c", "#e67e22"],
    mediumTri: ["#f1c40f"],
    smallTri: ["#2ecc71", "#3498db"],
    square: ["#9b59b6"],
    parallelogram: ["#e84393"]
  };

  function rotatePt(p, a) {
    var c = Math.cos(a), s = Math.sin(a);
    return [p[0] * c - p[1] * s, p[0] * s + p[1] * c];
  }

  function applyT(p, t) {
    var q = t.flip ? [-p[0], p[1]] : [p[0], p[1]];
    q = rotatePt(q, t.angle);
    return [q[0] + t.dx, q[1] + t.dy];
  }

  function transformPoly(poly, t) {
    return poly.map(function (p) { return applyT(p, t); });
  }

  function edgeOf(poly, idx) {
    var n = poly.length;
    return [poly[idx], poly[(idx + 1) % n]];
  }

  // Computes transform t so that local Q1 -> world P2 and local Q2 -> world P1
  // (edges of two adjacent CCW polygons run in opposite directions).
  function attachEdge(P1, P2, Q1, Q2, flip) {
    var q1 = flip ? [-Q1[0], Q1[1]] : [Q1[0], Q1[1]];
    var q2 = flip ? [-Q2[0], Q2[1]] : [Q2[0], Q2[1]];
    var dWorld = [P1[0] - P2[0], P1[1] - P2[1]];
    var dLocal = [q2[0] - q1[0], q2[1] - q1[1]];
    var angle = Math.atan2(dWorld[1], dWorld[0]) - Math.atan2(dLocal[1], dLocal[0]);
    var c = Math.cos(angle), s = Math.sin(angle);
    var rq1 = [q1[0] * c - q1[1] * s, q1[0] * s + q1[1] * c];
    var dx = P2[0] - rq1[0];
    var dy = P2[1] - rq1[1];
    return { dx: dx, dy: dy, angle: angle, flip: !!flip };
  }

  function polygonArea(poly) {
    var sum = 0;
    for (var i = 0; i < poly.length; i++) {
      var a = poly[i], b = poly[(i + 1) % poly.length];
      sum += a[0] * b[1] - b[0] * a[1];
    }
    return Math.abs(sum) / 2;
  }

  function centroidOf(poly) {
    var sx = 0, sy = 0;
    poly.forEach(function (p) { sx += p[0]; sy += p[1]; });
    return [sx / poly.length, sy / poly.length];
  }

  // A level is a flat list of "slots": where each of the 7 (or fewer, for
  // warm-up levels) pieces needs to end up, identified by SHAPE only (not by
  // a specific physical piece id) - any piece of that shape may fill any
  // matching open slot. dx/dy/angle describe the slot's rigid transform in
  // unit space (angle in degrees); worldVerts/centroid are resolved below.
  function resolveSlots(slots) {
    return slots.map(function (s) {
      var shape = SHAPES[s.shape];
      var t = { dx: s.dx, dy: s.dy, angle: s.angle * Math.PI / 180, flip: !!s.flip };
      var worldVerts = transformPoly(shape, t);
      return {
        shape: s.shape,
        chiral: !!CHIRAL_SHAPES[s.shape],
        symmetry: SHAPE_SYMMETRY[s.shape] || 360,
        transform: t,
        localShape: shape,
        worldVerts: worldVerts,
        centroid: centroidOf(worldVerts)
      };
    });
  }

  // ---- Level definitions (procedurally generated, see /scratchpad generator) --
  var LEVELS = [
    { id: "lvl1", name: "모양 1", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }] },
    { id: "lvl2", name: "모양 2", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 180, flip: false }] },
    { id: "lvl3", name: "모양 3", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 0, flip: false }] },
    { id: "lvl4", name: "모양 4", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "mediumTri", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "largeTri", dx: -1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: -3, dy: 1, angle: 0, flip: false }] },
    { id: "lvl5", name: "모양 5", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: -1, dy: 1, angle: 90, flip: false }, { shape: "square", dx: 0, dy: 2, angle: 90, flip: false }] },
    { id: "lvl6", name: "모양 6", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "mediumTri", dx: 0, dy: -2, angle: 90, flip: false }, { shape: "parallelogram", dx: -2, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: -2, dy: -1, angle: 270, flip: false }, { shape: "square", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: -2, dy: -2, angle: 90, flip: false }] },
    { id: "lvl7", name: "모양 7", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 2, dy: -2, angle: 0, flip: false }, { shape: "parallelogram", dx: 2, dy: 1, angle: 270, flip: false }] },
    { id: "lvl8", name: "모양 8", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "smallTri", dx: 1, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: -1, angle: 270, flip: false }, { shape: "largeTri", dx: 2, dy: 1, angle: 270, flip: false }, { shape: "largeTri", dx: 4, dy: 1, angle: 90, flip: false }] },
    { id: "lvl9", name: "모양 9", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 90, flip: false }, { shape: "square", dx: -1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 180, flip: false }] },
    { id: "lvl10", name: "모양 10", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: -2, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: -2, dy: 0, angle: 90, flip: false }] },
    { id: "lvl11", name: "모양 11", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 0, dy: 2, angle: 270, flip: false }, { shape: "mediumTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "square", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 2, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 4, angle: 180, flip: false }] },
    { id: "lvl12", name: "모양 12", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -2, dy: 1, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 2, angle: 90, flip: false }, { shape: "square", dx: 1, dy: 2, angle: 90, flip: false }] },
    { id: "lvl13", name: "모양 13", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "square", dx: 1, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: 2, dy: 0, angle: 90, flip: false }, { shape: "mediumTri", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: -1, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: 3, angle: 180, flip: false }] },
    { id: "lvl14", name: "모양 14", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "square", dx: 2, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 90, flip: false }, { shape: "parallelogram", dx: 2, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 90, flip: false }] },
    { id: "lvl15", name: "모양 15", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "parallelogram", dx: 0, dy: -1, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: -1, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 0, dy: -2, angle: 90, flip: false }] },
    { id: "lvl16", name: "모양 16", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 2, dy: -2, angle: 90, flip: false }, { shape: "mediumTri", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 3, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 1, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 1, dy: -3, angle: 0, flip: false }] },
    { id: "lvl17", name: "모양 17", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "parallelogram", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: 0, dy: 2, angle: 180, flip: false }, { shape: "square", dx: 1, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 0, dy: -2, angle: 90, flip: false }] },
    { id: "lvl18", name: "모양 18", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 1, dy: -2, angle: 90, flip: false }, { shape: "square", dx: 1, dy: -2, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "smallTri", dx: 1, dy: -2, angle: 270, flip: false }] },
    { id: "lvl19", name: "모양 19", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "smallTri", dx: 0, dy: 2, angle: 270, flip: false }, { shape: "mediumTri", dx: 1, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 2, dy: 2, angle: 90, flip: false }, { shape: "largeTri", dx: 3, dy: -1, angle: 90, flip: false }] },
    { id: "lvl20", name: "모양 20", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "square", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "largeTri", dx: -1, dy: -1, angle: 90, flip: false }, { shape: "largeTri", dx: -3, dy: 1, angle: 270, flip: false }] },
    { id: "lvl21", name: "모양 21", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: 2, angle: 180, flip: false }, { shape: "parallelogram", dx: 1, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 1, dy: -2, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: -2, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: 0, angle: 0, flip: false }] },
    { id: "lvl22", name: "모양 22", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 2, dy: -2, angle: 90, flip: false }, { shape: "square", dx: 2, dy: -1, angle: 270, flip: false }, { shape: "mediumTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 0, dy: 3, angle: 270, flip: false }] },
    { id: "lvl23", name: "모양 23", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "smallTri", dx: 2, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 4, dy: 1, angle: 180, flip: false }, { shape: "square", dx: 1, dy: -1, angle: 270, flip: false }] },
    { id: "lvl24", name: "모양 24", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 4, dy: -1, angle: 180, flip: false }, { shape: "smallTri", dx: 3, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 3, dy: -2, angle: 180, flip: false }] },
    { id: "lvl25", name: "모양 25", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "square", dx: 1, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 0, dy: -2, angle: 0, flip: false }, { shape: "mediumTri", dx: 1, dy: 0, angle: 90, flip: false }, { shape: "largeTri", dx: 1, dy: 2, angle: 270, flip: false }, { shape: "largeTri", dx: 3, dy: 0, angle: 90, flip: false }] },
    { id: "lvl26", name: "모양 26", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "parallelogram", dx: 1, dy: 1, angle: 270, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 90, flip: false }, { shape: "square", dx: 1, dy: 2, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 4, dy: 2, angle: 180, flip: false }] },
    { id: "lvl27", name: "모양 27", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "parallelogram", dx: -1, dy: 1, angle: 0, flip: false }, { shape: "mediumTri", dx: -1, dy: 3, angle: 270, flip: false }, { shape: "square", dx: 1, dy: 2, angle: 90, flip: false }, { shape: "largeTri", dx: -1, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: -3, dy: 1, angle: 270, flip: false }] },
    { id: "lvl28", name: "모양 28", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: -2, dy: -1, angle: 0, flip: false }, { shape: "parallelogram", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: -1, angle: 90, flip: false }, { shape: "square", dx: -2, dy: 0, angle: 180, flip: false }] },
    { id: "lvl29", name: "모양 29", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 2, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 3, dy: 1, angle: 180, flip: false }, { shape: "square", dx: 3, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: 3, dy: 0, angle: 0, flip: false }] },
    { id: "lvl30", name: "모양 30", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "mediumTri", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: -1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: -3, dy: -1, angle: 0, flip: false }] },
    { id: "lvl31", name: "모양 31", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "square", dx: 1, dy: 0, angle: 270, flip: false }, { shape: "mediumTri", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: -1, dy: -3, angle: 0, flip: false }] },
    { id: "lvl32", name: "모양 32", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 1, dy: 2, angle: 270, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 90, flip: false }, { shape: "square", dx: 2, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 2, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: 2, dy: 2, angle: 180, flip: false }] },
    { id: "lvl33", name: "모양 33", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "parallelogram", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 3, angle: 270, flip: false }, { shape: "largeTri", dx: 0, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: -2, dy: 3, angle: 270, flip: false }] },
    { id: "lvl34", name: "모양 34", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "parallelogram", dx: -1, dy: 2, angle: 0, flip: false }, { shape: "smallTri", dx: -1, dy: 3, angle: 270, flip: false }, { shape: "square", dx: 0, dy: 3, angle: 0, flip: false }] },
    { id: "lvl35", name: "모양 35", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 3, dy: 1, angle: 180, flip: false }, { shape: "mediumTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: -3, angle: 0, flip: false }] },
    { id: "lvl36", name: "모양 36", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 2, dy: -2, angle: 0, flip: false }, { shape: "smallTri", dx: 4, dy: -2, angle: 90, flip: false }, { shape: "square", dx: 2, dy: -3, angle: 0, flip: false }, { shape: "smallTri", dx: 4, dy: -2, angle: 180, flip: false }] },
    { id: "lvl37", name: "모양 37", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "square", dx: -2, dy: 2, angle: 270, flip: false }, { shape: "parallelogram", dx: 1, dy: 3, angle: 180, flip: false }] },
    { id: "lvl38", name: "모양 38", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "square", dx: 2, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: 3, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 2, dy: -1, angle: 180, flip: false }] },
    { id: "lvl39", name: "모양 39", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: 1, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 270, flip: false }, { shape: "mediumTri", dx: 2, dy: -2, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 270, flip: false }, { shape: "largeTri", dx: 4, dy: -4, angle: 90, flip: false }] },
    { id: "lvl40", name: "모양 40", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 0, dy: 2, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 3, angle: 270, flip: false }, { shape: "parallelogram", dx: 2, dy: 2, angle: 90, flip: false }, { shape: "square", dx: 0, dy: 4, angle: 270, flip: false }, { shape: "smallTri", dx: 2, dy: 4, angle: 180, flip: false }] },
    { id: "lvl41", name: "모양 41", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -2, dy: 1, angle: 0, flip: false }, { shape: "square", dx: -2, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 180, flip: false }] },
    { id: "lvl42", name: "모양 42", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: 1, dy: 2, angle: 270, flip: false }, { shape: "square", dx: 1, dy: 2, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: -2, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 90, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 270, flip: false }] },
    { id: "lvl43", name: "모양 43", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: 3, dy: 0, angle: 90, flip: false }, { shape: "parallelogram", dx: 3, dy: 1, angle: 90, flip: false }, { shape: "smallTri", dx: 3, dy: 1, angle: 0, flip: false }, { shape: "square", dx: 3, dy: -1, angle: 90, flip: false }] },
    { id: "lvl44", name: "모양 44", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "mediumTri", dx: 1, dy: 0, angle: 90, flip: false }, { shape: "parallelogram", dx: -2, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: -2, dy: -1, angle: 270, flip: false }, { shape: "largeTri", dx: 1, dy: 2, angle: 270, flip: false }, { shape: "largeTri", dx: 3, dy: 0, angle: 90, flip: false }] },
    { id: "lvl45", name: "모양 45", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 1, dy: -1, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: 1, angle: 270, flip: false }, { shape: "largeTri", dx: 4, dy: 1, angle: 90, flip: false }] },
    { id: "lvl46", name: "모양 46", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "parallelogram", dx: 0, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }] },
    { id: "lvl47", name: "모양 47", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: 0, dy: 2, angle: 180, flip: false }, { shape: "square", dx: -1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 0, flip: false }] },
    { id: "lvl48", name: "모양 48", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "mediumTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: -3, angle: 0, flip: false }] },
    { id: "lvl49", name: "모양 49", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "mediumTri", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 3, dy: -2, angle: 90, flip: false }, { shape: "square", dx: 1, dy: -1, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 90, flip: false }] },
    { id: "lvl50", name: "모양 50", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 270, flip: false }, { shape: "parallelogram", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "square", dx: -1, dy: 0, angle: 270, flip: false }] },
    { id: "lvl51", name: "모양 51", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 0, angle: 90, flip: false }, { shape: "square", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 90, flip: false }, { shape: "mediumTri", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: -1, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: 3, angle: 180, flip: false }] },
    { id: "lvl52", name: "모양 52", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "parallelogram", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 0, dy: 3, angle: 270, flip: false }] },
    { id: "lvl53", name: "모양 53", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "parallelogram", dx: -2, dy: 3, angle: 270, flip: false }, { shape: "smallTri", dx: -1, dy: 3, angle: 180, flip: false }, { shape: "square", dx: -1, dy: 4, angle: 180, flip: false }] },
    { id: "lvl54", name: "모양 54", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 1, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 2, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 3, dy: -1, angle: 90, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }] },
    { id: "lvl55", name: "모양 55", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: -2, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "parallelogram", dx: 2, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 90, flip: false }, { shape: "square", dx: 3, dy: 1, angle: 180, flip: false }] },
    { id: "lvl56", name: "모양 56", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: 3, dy: 0, angle: 90, flip: false }, { shape: "parallelogram", dx: 3, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 4, dy: 1, angle: 180, flip: false }, { shape: "square", dx: 4, dy: 0, angle: 0, flip: false }] },
    { id: "lvl57", name: "모양 57", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 2, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 0, flip: false }] },
    { id: "lvl58", name: "모양 58", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "parallelogram", dx: 3, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 3, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 2, dy: -2, angle: 90, flip: false }] },
    { id: "lvl59", name: "모양 59", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 0, dy: 3, angle: 270, flip: false }, { shape: "largeTri", dx: 0, dy: 3, angle: 0, flip: false }] },
    { id: "lvl60", name: "모양 60", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 3, dy: 0, angle: 180, flip: false }] },
    { id: "lvl61", name: "모양 61", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 90, flip: false }, { shape: "mediumTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 2, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 4, dy: -1, angle: 180, flip: false }] },
    { id: "lvl62", name: "모양 62", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 90, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 270, flip: false }, { shape: "mediumTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: 2, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 4, angle: 180, flip: false }] },
    { id: "lvl63", name: "모양 63", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "mediumTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "square", dx: -1, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 0, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 3, angle: 180, flip: false }] },
    { id: "lvl64", name: "모양 64", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 270, flip: false }, { shape: "mediumTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "parallelogram", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 4, dy: -1, angle: 180, flip: false }] },
    { id: "lvl65", name: "모양 65", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 1, dy: -1, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "parallelogram", dx: 0, dy: -3, angle: 0, flip: false }] },
    { id: "lvl66", name: "모양 66", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: -1, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "mediumTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: -1, angle: 270, flip: false }] },
    { id: "lvl67", name: "모양 67", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: -2, angle: 0, flip: false }, { shape: "square", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 0, dy: 1, angle: 0, flip: false }] },
    { id: "lvl68", name: "모양 68", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: 3, dy: 0, angle: 90, flip: false }, { shape: "square", dx: 3, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 3, dy: 2, angle: 180, flip: false }, { shape: "parallelogram", dx: 2, dy: 2, angle: 0, flip: false }] },
    { id: "lvl69", name: "모양 69", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "mediumTri", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 2, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 1, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 3, dy: -2, angle: 90, flip: false }] },
    { id: "lvl70", name: "모양 70", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 90, flip: false }, { shape: "parallelogram", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: 1, dy: -2, angle: 90, flip: false }, { shape: "largeTri", dx: 1, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 3, dy: -2, angle: 90, flip: false }] },
    { id: "lvl71", name: "모양 71", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: -1, dy: -2, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 270, flip: false }] },
    { id: "lvl72", name: "모양 72", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 0, dy: -2, angle: 0, flip: false }, { shape: "parallelogram", dx: 3, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: -2, angle: 180, flip: false }] },
    { id: "lvl73", name: "모양 73", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 1, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "parallelogram", dx: 0, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 3, dy: 2, angle: 180, flip: false }] },
    { id: "lvl74", name: "모양 74", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 2, dy: 2, angle: 180, flip: false }] },
    { id: "lvl75", name: "모양 75", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "square", dx: 0, dy: 1, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: -1, dy: -3, angle: 0, flip: false }] },
    { id: "lvl76", name: "모양 76", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 270, flip: false }, { shape: "parallelogram", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 0, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: -2, angle: 0, flip: false }] },
    { id: "lvl77", name: "모양 77", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "parallelogram", dx: -2, dy: -1, angle: 0, flip: false }, { shape: "square", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 1, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 1, dy: -3, angle: 0, flip: false }] },
    { id: "lvl78", name: "모양 78", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: 0, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: -2, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 1, dy: 2, angle: 180, flip: false }, { shape: "largeTri", dx: -2, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: -2, dy: 0, angle: 180, flip: false }] },
    { id: "lvl79", name: "모양 79", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "square", dx: 1, dy: 1, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: -1, dy: 3, angle: 270, flip: false }] },
    { id: "lvl80", name: "모양 80", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: -2, dy: 2, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 3, angle: 180, flip: false }, { shape: "square", dx: -2, dy: 1, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: 3, angle: 180, flip: false }, { shape: "smallTri", dx: -2, dy: 1, angle: 0, flip: false }] },
    { id: "lvl81", name: "모양 81", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 0, angle: 90, flip: false }, { shape: "square", dx: 2, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: 3, angle: 270, flip: false }, { shape: "largeTri", dx: 4, dy: 1, angle: 90, flip: false }] },
    { id: "lvl82", name: "모양 82", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "mediumTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: -1, angle: 180, flip: false }, { shape: "square", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: -3, angle: 0, flip: false }] },
    { id: "lvl83", name: "모양 83", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 90, flip: false }, { shape: "parallelogram", dx: 1, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "largeTri", dx: -1, dy: -1, angle: 90, flip: false }, { shape: "largeTri", dx: -3, dy: 1, angle: 270, flip: false }] },
    { id: "lvl84", name: "모양 84", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "parallelogram", dx: 0, dy: 1, angle: 0, flip: false }, { shape: "smallTri", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "mediumTri", dx: 1, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: 1, angle: 270, flip: false }, { shape: "largeTri", dx: 3, dy: -1, angle: 90, flip: false }] },
    { id: "lvl85", name: "모양 85", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: 0, dy: 1, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 2, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: -1, dy: -1, angle: 270, flip: false }, { shape: "largeTri", dx: -1, dy: -3, angle: 90, flip: false }] },
    { id: "lvl86", name: "모양 86", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "parallelogram", dx: -2, dy: -1, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 90, flip: false }, { shape: "largeTri", dx: 0, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 0, dy: 3, angle: 270, flip: false }] },
    { id: "lvl87", name: "모양 87", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "mediumTri", dx: 0, dy: 1, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 0, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 3, angle: 180, flip: false }, { shape: "square", dx: 0, dy: 0, angle: 180, flip: false }] },
    { id: "lvl88", name: "모양 88", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: 0, dy: 2, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 270, flip: false }, { shape: "parallelogram", dx: 3, dy: -2, angle: 90, flip: false }] },
    { id: "lvl89", name: "모양 89", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 1, dy: -1, angle: 90, flip: false }, { shape: "mediumTri", dx: 1, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: 2, angle: 270, flip: false }, { shape: "parallelogram", dx: 1, dy: -1, angle: 180, flip: false }, { shape: "largeTri", dx: 1, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 3, dy: 2, angle: 180, flip: false }] },
    { id: "lvl90", name: "모양 90", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "square", dx: -1, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 0, flip: false }] },
    { id: "lvl91", name: "모양 91", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "parallelogram", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: 1, dy: -2, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 180, flip: false }, { shape: "square", dx: 2, dy: -3, angle: 90, flip: false }] },
    { id: "lvl92", name: "모양 92", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "parallelogram", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "square", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: 2, dy: 3, angle: 270, flip: false }] },
    { id: "lvl93", name: "모양 93", slots: [{ shape: "mediumTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 2, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 0, flip: false }, { shape: "parallelogram", dx: 1, dy: 3, angle: 270, flip: false }, { shape: "square", dx: 1, dy: 2, angle: 180, flip: false }, { shape: "largeTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 2, dy: -2, angle: 90, flip: false }] },
    { id: "lvl94", name: "모양 94", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "largeTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: -1, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: 1, angle: 90, flip: false }, { shape: "square", dx: -2, dy: 1, angle: 270, flip: false }] },
    { id: "lvl95", name: "모양 95", slots: [{ shape: "square", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 270, flip: false }, { shape: "parallelogram", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: 1, angle: 0, flip: false }, { shape: "mediumTri", dx: 1, dy: -2, angle: 90, flip: false }, { shape: "largeTri", dx: 1, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: 3, dy: 0, angle: 90, flip: false }] },
    { id: "lvl96", name: "모양 96", slots: [{ shape: "parallelogram", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 1, dy: 2, angle: 270, flip: false }, { shape: "mediumTri", dx: 1, dy: 1, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 1, dy: 2, angle: 0, flip: false }, { shape: "largeTri", dx: 1, dy: 1, angle: 90, flip: false }, { shape: "largeTri", dx: -1, dy: 3, angle: 270, flip: false }] },
    { id: "lvl97", name: "모양 97", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }, { shape: "mediumTri", dx: 2, dy: 0, angle: 180, flip: false }, { shape: "parallelogram", dx: 1, dy: -2, angle: 90, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 180, flip: false }, { shape: "smallTri", dx: 2, dy: -1, angle: 90, flip: false }, { shape: "square", dx: 1, dy: -1, angle: 270, flip: false }] },
    { id: "lvl98", name: "모양 98", slots: [{ shape: "largeTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "mediumTri", dx: 0, dy: 0, angle: 90, flip: false }, { shape: "parallelogram", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: -1, dy: 2, angle: 270, flip: false }, { shape: "square", dx: -1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: 2, dy: 2, angle: 180, flip: false }] },
    { id: "lvl99", name: "모양 99", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "square", dx: 0, dy: -1, angle: 0, flip: false }, { shape: "parallelogram", dx: 1, dy: 0, angle: 270, flip: false }, { shape: "smallTri", dx: 0, dy: 0, angle: 180, flip: false }, { shape: "mediumTri", dx: -1, dy: 0, angle: 270, flip: false }, { shape: "largeTri", dx: -1, dy: -2, angle: 90, flip: false }, { shape: "largeTri", dx: -3, dy: -2, angle: 270, flip: false }] },
    { id: "lvl100", name: "모양 100", slots: [{ shape: "smallTri", dx: 0, dy: 0, angle: 0, flip: false }, { shape: "parallelogram", dx: -1, dy: -1, angle: 0, flip: false }, { shape: "mediumTri", dx: -1, dy: 1, angle: 270, flip: false }, { shape: "smallTri", dx: 0, dy: 1, angle: 180, flip: false }, { shape: "square", dx: -1, dy: 1, angle: 0, flip: false }, { shape: "largeTri", dx: -1, dy: 1, angle: 180, flip: false }, { shape: "largeTri", dx: -3, dy: -1, angle: 0, flip: false }] }
  ];

  var api = {
    SHAPES: SHAPES,
    SHAPE_SYMMETRY: SHAPE_SYMMETRY,
    CHIRAL_SHAPES: CHIRAL_SHAPES,
    SHAPE_FLIP_ROTATE_OFFSET: SHAPE_FLIP_ROTATE_OFFSET,
    SHAPE_COLORS: SHAPE_COLORS,
    LEVELS: LEVELS,
    rotatePt: rotatePt,
    applyT: applyT,
    transformPoly: transformPoly,
    edgeOf: edgeOf,
    attachEdge: attachEdge,
    resolveSlots: resolveSlots,
    polygonArea: polygonArea,
    centroidOf: centroidOf
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  } else {
    root.TangramData = api;
  }
})(typeof window !== "undefined" ? window : globalThis);
